### ISSUE TITLE
Las fichas de las casas gratuitas siguen mostrándolo todo

### ISSUE THREAD

**Issue by PaulJBis** [PaulJBis/AventurasRurales#3]
Las fichas de las casas gratuitas deberían tener los límites que se han especificado. Esto no se ha implementado aún.

**Comment by albertoeps** [comment]
Añadido

**Comment by PaulJBis** [comment]
Quitar também vídeos de Youtube y calendario de ocupación.

**Comment by PaulJBis** [comment]
Ahora no se ven las fotos, pero sí el thumbnail del vídeo. Corregir esto.

**Comment by PaulJBis** [comment]
OK.
